### PR TITLE
Corrected typo.

### PR DESCRIPTION
**Pull request by naunga**
Corrected README. Environment was spelled incorrectly.

### CODE REVIEW

**Comment by yahoocla** [comment]
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

**Comment by havetisyan** [comment]
@naunga I know it's a minor typo, but can you please follow the CLA link above and accept the term. Thanks.

**Comment by naunga** [comment]
I already did. 🙂

**Comment by mujibur** [comment]
👍

**Pull request merged**
